#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
@author: Alex
@date: 2020/05/21 14:18:24
@file: config.py
@usage: TODO
"""
from collections import namedtuple


# (index:首页[必填], list_format:翻页format[必填], max_pages:总页数[必填],
# list_xpath:列表xpath[必填], handler:必填, category:必填,
# website:必填, proxy_type:代理类型[选填 or None], redis_key:必填,
# title_xpath:内容标题xpath[选填 or None], attach_xpath:附件xpath[选填 or None],
# second_num:第二页开始数字[选填 or None])
UrlConfig = namedtuple('UrlConfig', ['index', 'list_format', 'max_pages',
                                     'list_xpath', 'handler', 'category',
                                     'website', 'proxy_type', 'redis_key',
                                     'title_xpath', 'attach_xpath', 'second_num'])

CONFIG = [
    # UrlConfig("http://www.pbc.gov.cn/fanxiqianju/135153/135173/20825/index1.html",
    #           "http://www.pbc.gov.cn/fanxiqianju/135153/135173/20825/index{}.html",
    #           2,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页>公开目录',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/rmyh/105208/8532/index1.html",
    #           "http://www.pbc.gov.cn/rmyh/105208/8532/index{}.html",
    #           8,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 公告信息',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/goutongjiaoliu/113456/113469/11040/index1.html",
    #           "http://www.pbc.gov.cn/goutongjiaoliu/113456/113469/11040/index{}.html",
    #           15,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 沟通交流 > 新闻',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/goutongjiaoliu/113456/113469/11040/index1.html",
    #           "http://www.pbc.gov.cn/goutongjiaoliu/113456/113469/11040/index{}.html",
    #           15,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 沟通交流 > 新闻',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/guokuju/136142/136152/21603/index1.html",
    #           "http://www.pbc.gov.cn/guokuju/136142/136152/21603/index{}.html",
    #           2,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 国库局 > 规章制度',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/guokuju/136142/136152/21603/index1.html",
    #           "http://www.pbc.gov.cn/guokuju/136142/136152/21603/index{}.html",
    #           2,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 国库局 > 规章制度',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/kuaijicaiwusi/145920/145974/index.html",
    #           "http://www.pbc.gov.cn/guokuju/136142/136152/21603/index{}.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 国库局 > 规章制度',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    # UrlConfig("http://www.pbc.gov.cn/huobijinyinju/147948/147966/23370/index1.html",
    #           "http://www.pbc.gov.cn/huobijinyinju/147948/147966/23370/index{}.html",
    #           11,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币金银局 > 贵金属纪念币',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/huobijinyinju/147948/161763/index.html",
    #           "http://www.pbc.gov.cn/huobijinyinju/147948/161763/index.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币金银局 > 贵金属纪念币',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    # UrlConfig("http://www.pbc.gov.cn/huobijinyinju/147948/161763/index.html",
    #           "http://www.pbc.gov.cn/huobijinyinju/147948/161763/index.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币金银局 > 人民币管理',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    # UrlConfig("http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125478/index.html",
    #           "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125478/index.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币政策司 > 货币政策工具 > 公开市场业务 > 短期流动性调节工具',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    # UrlConfig("http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125469/17079/index1.html",
    #           "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125469/17079/index{}.html",
    #           4,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币政策司 > 货币政策工具 > 公开市场业务 > 公开市场业务公告',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125475/17081/index1.html",
    #           "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125475/17081/index{}.html",
    #           109,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币政策司 > 货币政策工具 > 公开市场业务 > 公开市场业务交易公告',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125481/34af3845/index1.html",
    #           "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125481/34af3845/index{}.html",
    #           13,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币政策司 > 货币政策工具 > 公开市场业务 > 中央国库现金管理业务公告',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125472/17080/index1.html",
    #           "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125431/125472/17080/index{}.html",
    #           36,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币政策司 > 货币政策工具 > 公开市场业务 > 中央银行票据发行公告',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125437/125815/index.html",
    #           "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125437/125815/index.html",
    #           2,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币政策司 > 货币政策工具 > 中央银行贷款 > 再贷款政策与制度',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    # UrlConfig("http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125437/125815/index.html",
    #           "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125437/125815/index.html",
    #           2,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币政策司 > 货币政策工具 > 中央银行贷款 > 再贷款政策与制度',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    # UrlConfig("http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125437/125818/index.html",
    #           "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125437/125818/index.html",
    #           2,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 货币政策司 > 货币政策工具 > 中央银行贷款 > 再贴现政策与制度',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    # UrlConfig("http://www.pbc.gov.cn/jinrongshichangsi/147160/147171/147367/22937/index1.html",
    #           "http://www.pbc.gov.cn/jinrongshichangsi/147160/147171/147367/22937/index{}.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 金融市场司 > 金融市场 > 房地产与汽车金融',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    #
    # UrlConfig("http://www.pbc.gov.cn/jinrongshichangsi/147160/147171/147361/147418/index.html",
    #           "http://www.pbc.gov.cn/jinrongshichangsi/147160/147171/147361/147418/index.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 金融市场司 > 金融市场 > 黄金与外汇市场 > 政策法规',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    #
    # UrlConfig("http://www.pbc.gov.cn/jinrongshichangsi/147160/147171/147355/147383/index.html",
    #           "http://www.pbc.gov.cn/jinrongshichangsi/147160/147171/147355/147383/index.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 金融市场司 > 金融市场 > 货币市场 > 政策法规',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    #
    # UrlConfig("http://www.pbc.gov.cn/jinrongshichangsi/147160/147171/147358/147400/22928/index1.html",
    #           "http://www.pbc.gov.cn/jinrongshichangsi/147160/147171/147358/147400/22928/index{}.html",
    #           4,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 金融市场司 > 金融市场 > 银行间债券市场 > 政策法规',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/jinrongshichangsi/147160/147289/147301/22922/index1.html",
    #           "http://www.pbc.gov.cn/jinrongshichangsi/147160/147289/147301/22922/index{}.html",
    #           5,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 金融市场司 > 信贷政策 > 政策法规',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           2),
    # UrlConfig("http://www.pbc.gov.cn/jinrongwendingju/146766/146772/index.html",
    #           "http://www.pbc.gov.cn/jinrongwendingju/146766/146772/index.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 金融稳定局 > 金融风险监测评估',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),
    #
    # UrlConfig("http://www.pbc.gov.cn/jinrongwendingju/146766/146770/index.html",
    #           "http://www.pbc.gov.cn/jinrongwendingju/146766/146770/index.html",
    #           1,
    #           "//font[@class='newslist_style']/a/@href",
    #           '1-proxy-pbc',
    #           u'首页 > 金融稳定局 > 金融体制改革',
    #           u'中国人民银行',
    #           'abuyun',
    #           'policy:mofcom:class01',
    #           None,
    #           None,
    #           None),

    UrlConfig("http://www.pbc.gov.cn/jingrxfqy/145720/145728/index.html",
              "http://www.pbc.gov.cn/jingrxfqy/145720/145728/index.html",
              1,
              "//font[@class='newslist_style']/a/@href",
              '1-proxy-pbc',
              u'首页 > 金融消费权益保护局 > 政策法规',
              u'中国人民银行',
              'abuyun',
              'policy:mofcom:class01',
              None,
              None,
              None),





]


if __name__ == '__main__':
    for config in CONFIG:
        print config.index
