redis_config:
  host: 47.105.54.129
  port: 6388
  password: admin
mongo_config:
  host: 47.105.54.129
  posrt: 27017
  database: shixin
  password: scc57295729
site_config:
  host: .cngold.com.cn
  index: http://www.cngold.com.cn