redis_config:
  host: 47.105.54.129
  port: 6388
  password: admin

mongo_config:
  host: 47.105.54.129
  posrt: 27017
  database: shixin
  user: chean
  password: scc57295729
  collection: TencentNews

site_config:
  host: new.qq.com
  index: https://news.qq.com/
  base_url: https://pacaio.match.qq.com/irs/rcd?cid={id}&token={token}&ext={id_name}&page={page}
  category:


parse_config:
  title: string(//title)
  publish_time: string(//div[@class='new_tit_ch']/span[2])
  source: substring-after(//div[@class='new_tit_ch']/span[1]/text(),'：')
  sitename: string('腾讯新闻')
  source_type: string('新闻')
  author: string('')